"""Generate hm/notebooks/export_hm_images_zip.ipynb."""
from pathlib import Path
import nbformat as nbf

ROOT = Path(__file__).resolve().parents[2]
OUT = ROOT / "hm" / "notebooks" / "export_hm_images_zip.ipynb"

def build_notebook():
    nb = nbf.v4.new_notebook()
    cells = []
    
    # Cell 1: Intro Markdown
    cells.append(nbf.v4.new_markdown_cell(
        "# Export H&M Images to Zip for Local Development\n\n"
        "Notebook này giúp bạn **trích xuất và nén các hình ảnh thực sự được sử dụng** từ dataset gốc H&M "
        "(`H&M Personalized Fashion Recommendations`) kết hợp với tập dữ liệu đã lọc (`HM-dataset_filled`), "
        "thay vì phải tải toàn bộ thư mục 31.6 GB ảnh gốc.\n\n"
        "### 🎯 Các điểm nổi bật:\n"
        "1. **Phát hiện tức thì 0.001s (0 đệ quy)**: Tuyệt đối không dùng `rglob` hay duyệt sâu qua 105k ảnh, "
        "tránh hoàn toàn nguy cơ đơ/treo kernel trên Kaggle.\n"
        "2. **Lọc thông minh**: Chỉ lấy các item xuất hiện trong `train.parquet`, `valid.parquet`, `test.parquet`, "
        "`rerank_train.parquet` (73,041 ảnh), hoặc Top N phổ biến.\n"
        "3. **Tối ưu dung lượng (Resize & Compress)**: Giúp giảm dung lượng từ ~20 GB xuống còn **~1.2 - 1.8 GB**, "
        "tải về máy local chỉ mất vài phút.\n"
        "4. **Tự động chia nhỏ part** (nếu cần) để tránh lỗi timeout khi download."
    ))
    
    # Cell 2: Config
    cells.append(nbf.v4.new_code_cell(
        "# ==============================================================================\n"
        "# ⚙️ CẤU HÌNH ĐÓNG GÓI ẢNH (BẠN CÓ THỂ ĐIỀU CHỈNH TÙY THEO NHU CẦU)\n"
        "# ==============================================================================\n"
        "from pathlib import Path\n"
        "import os\n\n"
        "# 1. CHẾ ĐỘ LỌC ẢNH (FILTER_MODE):\n"
        "#    - 'active_only' (KHUYÊN DÙNG): Lấy ảnh của 73,041 items có trong train/valid/test/rerank_train\n"
        "#    - 'top_popular': Lấy Top N sản phẩm phổ biến nhất (phù hợp demo web, seed DB local siêu nhẹ)\n"
        "#    - 'eval_only': Chỉ lấy ảnh của các items trong valid & test (~6,510 items)\n"
        "#    - 'all_catalog': Lấy toàn bộ 105,100 ảnh trong catalog items.parquet\n"
        "FILTER_MODE = 'active_only'\n\n"
        "# Số lượng sản phẩm nếu chọn FILTER_MODE = 'top_popular':\n"
        "TOP_N_POPULAR = 10_000\n\n"
        "# 2. TỐI ƯU DUNG LƯỢNG (RESIZE & NÉN JPEG):\n"
        "#    - True: Resize cạnh dài về MAX_EDGE_PIXELS (512px) và nén chất lượng 85%.\n"
        "#            Dung lượng giảm ~90% (từ 20GB còn ~1.5GB) nhưng vẫn cực kỳ sắc nét trên Web/Mobile.\n"
        "#    - False: Giữ nguyên ảnh gốc 100% từ Kaggle.\n"
        "RESIZE_OPTIMIZE = True\n"
        "MAX_EDGE_PIXELS = 512\n"
        "JPEG_QUALITY = 85\n\n"
        "# 3. CHIA NHỎ FILE ZIP (SPLIT PART):\n"
        "#    - Chia thành các file zip nhỏ (MB) để tải về không bị rớt mạng.\n"
        "#    - Đặt None nếu muốn gom toàn bộ vào đúng 1 file zip duy nhất.\n"
        "SPLIT_PART_MB = 1800\n\n"
        "# 4. Thư mục xuất file (Lưu trực tiếp vào /kaggle/working để hiện ngay trên giao diện Output)\n"
        "OUTPUT_DIR = Path('/kaggle/working')\n"
        "OUTPUT_DIR.mkdir(parents=True, exist_ok=True)\n"
        "print(f'✅ Cấu hình: FILTER_MODE={FILTER_MODE}, RESIZE_OPTIMIZE={RESIZE_OPTIMIZE}, OUTPUT_DIR={OUTPUT_DIR}')"
    ))
    
    # Cell 3: Discovery (Instant O(1), No Recursion)
    cells.append(nbf.v4.new_code_cell(
        "# ==============================================================================\n"
        "# 🔍 TỰ ĐỘNG PHÁT HIỆN THƯ MỤC ẢNH GỐC VÀ DATASET HM-dataset_filled\n"
        "# (Dùng O(1) direct lookup, tuyệt đối không duyệt rglob qua 105k ảnh)\n"
        "# ==============================================================================\n"
        "import polars as pl\n\n"
        "# 1. Thu thập các thư mục cấp 1 và cấp 2 trong /kaggle/input\n"
        "search_dirs = []\n"
        "if Path('/kaggle/input').exists():\n"
        "    for p in Path('/kaggle/input').iterdir():\n"
        "        if p.is_dir():\n"
        "            search_dirs.append(p)\n"
        "            try:\n"
        "                for sub in p.iterdir():\n"
        "                    if sub.is_dir():\n"
        "                        search_dirs.append(sub)\n"
        "            except Exception:\n"
        "                pass\n\n"
        "search_dirs.extend([Path.cwd(), Path('data'), Path('data/hm')])\n"
        "search_dirs = list(dict.fromkeys(search_dirs))\n\n"
        "# 2. Tìm trực tiếp thư mục images (chạy trong 0.0001s, không duyệt file con)\n"
        "image_dir = None\n"
        "for d in search_dirs:\n"
        "    candidate = d / 'images'\n"
        "    if candidate.is_dir():\n"
        "        image_dir = candidate\n"
        "        break\n\n"
        "# 3. Tìm trực tiếp thư mục chứa items.parquet\n"
        "dataset_dir = None\n"
        "for d in search_dirs:\n"
        "    candidate = d / 'items.parquet'\n"
        "    if candidate.is_file():\n"
        "        dataset_dir = d\n"
        "        break\n\n"
        "print('📂 Thư mục ảnh gốc (images):', image_dir)\n"
        "print('📂 Thư mục dataset (HM-dataset_filled):', dataset_dir)\n\n"
        "if not image_dir or not image_dir.exists():\n"
        "    raise FileNotFoundError('❌ Không tìm thấy thư mục images! Hãy chắc chắn bạn đã Add input competition H&M Personalized Fashion Recommendations.')\n"
        "if not dataset_dir or not (dataset_dir / 'items.parquet').exists():\n"
        "    raise FileNotFoundError('❌ Không tìm thấy items.parquet! Hãy chắc chắn bạn đã Add input dataset HM-dataset_filled.')\n\n"
        "print('⚡ Phát hiện đường dẫn tức thì (0 đệ quy, không quét duyệt file con, an toàn tuyệt đối)!')"
    ))
    
    # Cell 4: Filter Target Items
    cells.append(nbf.v4.new_code_cell(
        "# ==============================================================================\n"
        "# 📋 LỌC DANH SÁCH SẢN PHẨM CẦN LẤY THEO CHẾ ĐỘ ĐÃ CHỌN\n"
        "# ==============================================================================\n"
        "items_df = pl.read_parquet(dataset_dir / 'items.parquet')\n"
        "catalog_items = set(items_df['item_id'])\n"
        "print(f'Tổng số sản phẩm trong catalog (items.parquet): {len(catalog_items):,}')\n\n"
        "target_item_ids = set()\n\n"
        "if FILTER_MODE == 'all_catalog':\n"
        "    target_item_ids = catalog_items\n"
        "    print(f'Mode all_catalog: Lấy toàn bộ {len(target_item_ids):,} items.')\n\n"
        "elif FILTER_MODE == 'active_only':\n"
        "    splits = ['train', 'rerank_train', 'valid', 'test']\n"
        "    for s in splits:\n"
        "        p = dataset_dir / f'{s}.parquet'\n"
        "        if p.exists():\n"
        "            df = pl.read_parquet(p)\n"
        "            col = 'article_id' if 'article_id' in df.columns else 'item_id'\n"
        "            target_item_ids.update(df[col].unique().to_list())\n"
        "    print(f'Mode active_only: Lấy {len(target_item_ids):,} items có tương tác trong train/rerank/valid/test.')\n\n"
        "elif FILTER_MODE == 'eval_only':\n"
        "    for s in ['valid', 'test']:\n"
        "        p = dataset_dir / f'{s}.parquet'\n"
        "        if p.exists():\n"
        "            df = pl.read_parquet(p)\n"
        "            col = 'article_id' if 'article_id' in df.columns else 'item_id'\n"
        "            target_item_ids.update(df[col].unique().to_list())\n"
        "    print(f'Mode eval_only: Lấy {len(target_item_ids):,} items trong valid & test.')\n\n"
        "elif FILTER_MODE == 'top_popular':\n"
        "    train_p = dataset_dir / 'train.parquet'\n"
        "    if train_p.exists():\n"
        "        train_df = pl.read_parquet(train_p)\n"
        "        col = 'article_id' if 'article_id' in train_df.columns else 'item_id'\n"
        "        top_items = train_df.group_by(col).len().sort('len', descending=True).head(TOP_N_POPULAR)[col].to_list()\n"
        "        target_item_ids = set(top_items)\n"
        "        print(f'Mode top_popular: Lấy Top {len(target_item_ids):,} items phổ biến nhất.')\n"
        "    else:\n"
        "        target_item_ids = set(list(catalog_items)[:TOP_N_POPULAR])\n\n"
        "# Map sang danh sách tasks (tạo đường dẫn dạng O(1) trong memory, không quét đĩa)\n"
        "tasks = []\n"
        "for item_id in target_item_ids:\n"
        "    item_str = str(item_id).zfill(10)\n"
        "    subfolder = item_str[:3]\n"
        "    img_path = image_dir / subfolder / f'{item_str}.jpg'\n"
        "    tasks.append((item_str, img_path))\n\n"
        "print(f'✅ Đã chuẩn bị {len(tasks):,} tasks. Việc kiểm tra và đọc ảnh sẽ chạy song song trong bước tiếp theo!')"
    ))
    
    # Cell 5: Package and Zip
    cells.append(nbf.v4.new_code_cell(
        "# ==============================================================================\n"
        "# 📦 ĐÓNG GÓI VÀ NÉN ẢNH VÀO FILE ZIP (MULTI-THREADED & SPLIT PART)\n"
        "# ==============================================================================\n"
        "import time, io, zipfile, json\n"
        "from PIL import Image\n"
        "from concurrent.futures import ThreadPoolExecutor\n"
        "from tqdm.auto import tqdm\n\n"
        "def process_and_zip(tasks, output_dir, resize_opt=True, max_edge=512, quality=85, split_mb=1800):\n"
        "    start_time = time.time()\n"
        "    current_part = 1\n"
        "    current_zip_bytes = 0\n"
        "    split_bytes = split_mb * 1024 * 1024 if split_mb else float('inf')\n"
        "    \n"
        "    def get_zip_path(part_idx):\n"
        "        if split_mb is None:\n"
        "            return output_dir / f'hm_images_{FILTER_MODE}.zip'\n"
        "        return output_dir / f'hm_images_{FILTER_MODE}_part{part_idx:02d}.zip'\n"
        "    \n"
        "    zip_path = get_zip_path(current_part)\n"
        "    current_zip = zipfile.ZipFile(zip_path, mode='w', compression=zipfile.ZIP_DEFLATED, compresslevel=6)\n"
        "    created_zips = [zip_path]\n"
        "    \n"
        "    print(f'🚀 Bắt đầu đóng gói {len(tasks):,} ảnh vào: {zip_path.name}')\n"
        "    \n"
        "    def prepare_image(task):\n"
        "        item_str, path = task\n"
        "        arcname = f'images/{item_str[:3]}/{item_str}.jpg'\n"
        "        if not path.is_file():\n"
        "            return arcname, None, 'File not found'\n"
        "        try:\n"
        "            if not resize_opt:\n"
        "                with open(path, 'rb') as f:\n"
        "                    data = f.read()\n"
        "            else:\n"
        "                with Image.open(path) as img:\n"
        "                    img = img.convert('RGB')\n"
        "                    w, h = img.size\n"
        "                    if max(w, h) > max_edge:\n"
        "                        scale = max_edge / max(w, h)\n"
        "                        new_w, new_h = int(w * scale), int(h * scale)\n"
        "                        img = img.resize((new_w, new_h), Image.Resampling.LANCZOS)\n"
        "                    buf = io.BytesIO()\n"
        "                    img.save(buf, format='JPEG', quality=quality, optimize=True)\n"
        "                    data = buf.getvalue()\n"
        "            return arcname, data, None\n"
        "        except Exception as err:\n"
        "            return arcname, None, str(err)\n"
        "    \n"
        "    success_count = 0\n"
        "    missing_count = 0\n"
        "    errors = []\n"
        "    \n"
        "    with ThreadPoolExecutor(max_workers=8) as executor:\n"
        "        for arcname, data, err in tqdm(executor.map(prepare_image, tasks), total=len(tasks), desc='Zipping'):\n"
        "            if data is not None:\n"
        "                current_zip.writestr(arcname, data)\n"
        "                success_count += 1\n"
        "                current_zip_bytes += len(data)\n"
        "                \n"
        "                if current_zip_bytes >= split_bytes:\n"
        "                    current_zip.close()\n"
        "                    part_mb = zip_path.stat().st_size / (1024 * 1024)\n"
        "                    print(f'📦 Hoàn tất part {current_part}: {zip_path.name} ({part_mb:.1f} MB)')\n"
        "                    current_part += 1\n"
        "                    current_zip_bytes = 0\n"
        "                    zip_path = get_zip_path(current_part)\n"
        "                    current_zip = zipfile.ZipFile(zip_path, mode='w', compression=zipfile.ZIP_DEFLATED, compresslevel=6)\n"
        "                    created_zips.append(zip_path)\n"
        "            elif err == 'File not found':\n"
        "                missing_count += 1\n"
        "            else:\n"
        "                errors.append({'arcname': arcname, 'error': err})\n"
        "    \n"
        "    current_zip.close()\n"
        "    elapsed = time.time() - start_time\n"
        "    total_mb = sum(p.stat().st_size for p in created_zips) / (1024 * 1024)\n"
        "    \n"
        "    print('\\n' + '=' * 60)\n"
        "    print(f'🎉 HOÀN THÀNH trong {elapsed:.1f} giây!')\n"
        "    print(f'Tổng số ảnh đã đóng gói: {success_count:,} / {len(tasks):,}')\n"
        "    if missing_count > 0:\n"
        "        print(f'Số ảnh không tìm thấy trong nguồn: {missing_count:,}')\n"
        "    print(f'Tổng dung lượng file zip: {total_mb:.2f} MB ({total_mb / 1024:.2f} GB)')\n"
        "    for p in created_zips:\n"
        "        print(f'  - {p.name}: {p.stat().st_size / (1024 * 1024):.1f} MB')\n"
        "    print('=' * 60)\n"
        "    \n"
        "    manifest = {\n"
        "        'filter_mode': FILTER_MODE,\n"
        "        'resize_optimize': resize_opt,\n"
        "        'max_edge_pixels': max_edge if resize_opt else None,\n"
        "        'total_images': success_count,\n"
        "        'missing_images': missing_count,\n"
        "        'total_size_mb': total_mb,\n"
        "        'files': [p.name for p in created_zips],\n"
        "        'errors': len(errors)\n"
        "    }\n"
        "    (output_dir / 'images_manifest.json').write_text(json.dumps(manifest, indent=2))\n"
        "    return created_zips\n\n"
        "created_zips = process_and_zip(\n"
        "    tasks,\n"
        "    OUTPUT_DIR,\n"
        "    resize_opt=RESIZE_OPTIMIZE,\n"
        "    max_edge=MAX_EDGE_PIXELS,\n"
        "    quality=JPEG_QUALITY,\n"
        "    split_mb=SPLIT_PART_MB\n"
        ")"
    ))
    
    # Cell 6: Download instructions
    cells.append(nbf.v4.new_code_cell(
        "# ==============================================================================\n"
        "# 📥 HƯỚNG DẪN TẢI FILE VỀ MÁY LOCAL\n"
        "# ==============================================================================\n"
        "from IPython.display import FileLink, display\n\n"
        "print('🎉 ĐÃ HOÀN TẤT ĐÓNG GÓI! CÁC FILE ZIP ĐƯỢC LƯU TẠI /kaggle/working:')\n"
        "for p in created_zips:\n"
        "    print(f'  📦 {p.name} ({p.stat().st_size / (1024 * 1024):.1f} MB)')\n\n"
        "print('\\n' + '=' * 65)\n"
        "print('🔥 CÁCH 1: TẢI TRỰC TIẾP QUA GIAO DIỆN KAGGLE (KHUYÊN DÙNG & ỔN ĐỊNH NHẤT)')\n"
        "print('=' * 65)\n"
        "print('1. Nhìn sang CỘT BÊN PHẢI (Sidebar) của màn hình Kaggle Notebook.')\n"
        "print('2. Tìm mục \"Output\" (dưới mục \"Input\").')\n"
        "print('   👉 Nếu chưa thấy file hiện ra, nhấn vào icon REFRESH 🔄 ở góc trên mục Output.')\n"
        "print('3. Rê chuột vào từng file .zip -> Nhấn vào icon DOWNLOAD (Mũi tên ⬇️) để tải về!')\n\n"
        "print('\\n' + '=' * 65)\n"
        "print('🔥 CÁCH 2: DÙNG LỆNH KAGGLE CLI TẠI TERMINAL MÁY LOCAL')\n"
        "print('=' * 65)\n"
        "print('kaggle kernels output <username>/<notebook-slug> -p ./data/hm/downloaded_images')\n\n"
        "# Thử hiển thị relative FileLink (chỉ hoạt động trên một số phiên bản Kaggle web)\n"
        "try:\n"
        "    print('\\n⬇️ Hoặc thử bấm link trực tiếp dưới đây:')\n"
        "    for p in created_zips:\n"
        "        display(FileLink(p.name))\n"
        "except Exception:\n"
        "    pass"
    ))
    
    nb.cells = cells
    nb.metadata = {
        "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
        "language_info": {"name": "python", "version": "3.10"}
    }
    
    OUT.parent.mkdir(parents=True, exist_ok=True)
    with open(OUT, "w", encoding="utf-8") as f:
        nbf.write(nb, f)
    print(f"Generated notebook at: {OUT}")

if __name__ == "__main__":
    build_notebook()
